name: AxoSyslog stable image

permissions: write-all

on:
  workflow_dispatch:

jobs:
  pre-check:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'axoflow'
    steps:
      - name: Validate tag
        run: true

  publish-image:
    uses: ./.github/workflows/axosyslog-docker.yml
    needs: pre-check
    with:
      type: stable
